# 开发环境配置文件
spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyquiz?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # druid相关配置
    druid:
      max-active: 5000
      initial-size: 20
      min-idle: 5
      async-init: true
      # 监控统计
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          config:
            create-table-allow: false
            alter-table-allow: false
            drop-table-allow: false
            truncate-allow: false

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: repository.

pagehelper:
  #自动识别数据库方言
  auto-dialect: true
  #从方法参数中取值
  support-methods-arguments: true
  #数据库方言
  #helper-dialect: postgresql
  #动态切换数据源
  auto-runtime-dialect: true
  #启用合理化，根据页数自动适配
  reasonable: true
# 文件上传配置
conf:
  upload:
    # 物理文件存储位置，以/结束，windows已正斜杠，如：d:/exam-upload/
    dir: /Users/van/Documents/work/upload/
    # 访问地址，注意不要去除/upload/file/，此节点为虚拟标识符
    # 如：http://localhost:8101/upload/file/exam.jpg，对应物理文件为：/data/upload/exam.jpg
    url: http://localhost:8201/upload/file/
    # 允许上传的文件后缀
    allow-extensions: jpg,jpeg,png

# 开启文档
swagger:
  enable: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: logs/${spring.application.name}/